#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");
mkdirSync(dist, { recursive: true });

// Two skills, each with rules/. Skill folders contain the SKILL.md (the orientation
// doc that gets registered as the canonical summary).
const skillFolders = ["tps-best-practices", "flair-best-practices"];

const ruleNames = [];
const rules = {};
const skillSummaries = {};

for (const skill of skillFolders) {
  const summaryPath = join(root, skill, "SKILL.md");
  skillSummaries[skill] = readFileSync(summaryPath, "utf8");
  const rulesDir = join(root, skill, "rules");
  for (const filename of readdirSync(rulesDir).filter((f) => f.endsWith(".md")).sort()) {
    const ruleName = filename.replace(/\.md$/, "");
    const content = readFileSync(join(rulesDir, filename), "utf8");
    ruleNames.push(ruleName);
    rules[ruleName] = content;
  }
}

// Default skillSummary points at tps-best-practices (the entry point); flair-best-practices
// links from there. Callers wanting the flair one specifically can read from `rules`.
const skillSummary = skillSummaries["tps-best-practices"];

const js = `// Auto-generated by scripts/build.mjs. Do not edit.
export const ruleNames = ${JSON.stringify(ruleNames, null, 2)};

export const rules = ${JSON.stringify(rules, null, 2)};

export const skillSummary = ${JSON.stringify(skillSummary)};

export const skillSummaries = ${JSON.stringify(skillSummaries, null, 2)};
`;

const dts = `export declare const ruleNames: readonly string[];
export type RuleName = (typeof ruleNames)[number];
export declare const rules: Record<string, string>;
export declare const skillSummary: string;
export declare const skillSummaries: Record<string, string>;
`;

writeFileSync(join(dist, "index.js"), js);
writeFileSync(join(dist, "index.d.ts"), dts);

console.log(`✓ built ${ruleNames.length} rules across ${skillFolders.length} skills`);
